# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Sean Hackett
tagline:             'Large-Scale Statistics of <a href=academics>Genomics</a> and <a href="http://fightprior.com">Sports</a>'
description:         '<img src="https://raw.githubusercontent.com/shackett/shackett.github.io/master/public/boarding.png" width=200 </img> <br>I spend my days using tools from data science to wrangle big biological datasets. Most of my research involves modeling how yeast and cancer metabolism is shaped by genetics and the environment. The rest of my time I spend watching MMA and training BJJ.</br><br>Recently, I have been fusing these passions by applying exploratory data analysis to MMA and BJJ at <a href="https://fightprior.com">FightPrior.com</a>.</br>'
url:                 'http://www.fightprior.com'
#url:                 'http://127.0.0.1:4000'
paginate:            5
gems:                [jekyll-paginate]
excerpt_separator:   <!--more-->

# About/contact
author:
  name:              Sean Hackett
  url:               http://shackett.github.io/
  email:             TBD

# Custom vars
version:             2.0.0

# Build settings
markdown: kramdown
